### ISSUE TITLE
Output dumped to stdout instead of being returned

### ISSUE THREAD

**Issue by DarkWiiPlayer** [daelvn/tableview#2]
When calling `tableview.generate`, the HTML code is just printed on stdout instead of being returned as a string. This is because the `print` function for the MoonXML environment is never changed, and thus just calls the standard `print`.

The easiest fix would be to just pass in a custom `print` function that appends its arguments to a buffer table.

**Comment by daelvn** [comment]
(Waiting on DarkWiiPlayer/moonxml#1 to be ~~fixed~~ peacefully, voluntarily changed)

**Comment by DarkWiiPlayer** [comment]
I sure hope this gets fixed quickly in upstream, I'm depending on this to work for what I plan to use tableview for!

**Comment by daelvn** [comment]
Should be fixed by #4
